# Generated by Django 3.2.10 on 2022-01-04 16:16

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_eventparticipants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventParticipants',
            field=django_mysql.models.ListTextField(models.IntegerField(), default=0, null=True, size=50),
        ),
    ]
