# Generated by Django 3.2.10 on 2022-01-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profilePicture',
            field=models.URLField(default='https://avatar-management--avatars.us-west-2.prod.public.atl-paas.net/:/128'),
        ),
    ]
