# Generated by Django 4.0 on 2022-01-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='from_user',
            field=models.ForeignKey(default='accounts.CustomUser', on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to='accounts.customuser'),
        ),
    ]
